# Generated by Django 4.2.4 on 2023-09-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updater',
            new_name='updated',
        ),
    ]
